name = "qColoringCardinality"
uuid = "3fdf6bac-96d1-49b0-a177-5ab34bf54285"
authors = ["Diandre Miguel Sabale <dmbs@uw.edu>", "Kyle Deeds <kdeeds@cs.washington.edu>", "Moe Kayali <kayali@cs.washington.edu>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
QuasiStableColors = "9c3856af-3e7c-4d34-a6af-a406867b22e4"

[compat]
julia = "^1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
